// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {oidstorage} from '../models';

export function GetAllCurrentAgents():Promise<Array<agent.AgentObj>>;

export function GetCurrentOids():Promise<Array<oidstorage.Oid>>;

export function ParseMib():Promise<void>;

export function SendGetRequest():Promise<void>;

export function SendGetRequestWithOid(arg1:string):Promise<void>;
