// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentOids() {
  return window['go']['main']['App']['GetCurrentOids']();
}

export function ParseMib() {
  return window['go']['main']['App']['ParseMib']();
}
