// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCurrentAgents() {
  return window['go']['main']['App']['GetAllCurrentAgents']();
}

export function GetCurrentOids() {
  return window['go']['main']['App']['GetCurrentOids']();
}

export function ParseMib() {
  return window['go']['main']['App']['ParseMib']();
}

export function SendGetRequest() {
  return window['go']['main']['App']['SendGetRequest']();
}

export function SendGetRequestWithOid(arg1) {
  return window['go']['main']['App']['SendGetRequestWithOid'](arg1);
}
