// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {oidstorage} from '../models';

export function GetCurrentOids():Promise<Array<oidstorage.Oid>>;

export function ParseMib():Promise<void>;
